name: Firebase App Distribution

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  distribute-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Flutter pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Decode Android keystore
        shell: bash
        run: |
          printf '%s' "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Build release APK
        run: flutter build apk --release --flavor prod -t lib/main_prod.dart --build-name=1.0.0 --build-number=${{ github.run_number }}

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskflow-prod-release-apk
          path: build/app/outputs/flutter-apk/app-prod-release.apk
          retention-days: 7

      - name: Create Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-prod-release.apk \
            --app "${{ secrets.FIREBASE_APP_ID }}" \
            --groups "${{ secrets.FIREBASE_GROUPS }}" \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --release-notes "Build #${{ github.run_number }} - ${{ github.event.head_commit.message }}"
